-- auto-generated definition
create table expenses
(
    id      bigint generated by default as identity
        primary key,
    expense varchar(100),
    value   bigint default 0 not null
);

alter table expenses
    owner to postgres;

