services:
  postgres:
    image: postgres:16
    ports:
      - 54322:5432
    environment:
      - POSTGRES_PASSWORD=database_pass
      - POSTGRES_USER=database_user
      - POSTGRES_DB=spending_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

